project_name: vault-token-helper
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
builds:
  - binary: vault-token-helper
    id: macos
    ldflags: -s -w -X github.com/joemiller/vault-token-helper/cmd.version={{.Version}}+{{.ShortCommit}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: ./scripts/macos-codesign.sh "{{ .Path }}"

  # cross-compile windows binary
  - binary: vault-token-helper
    id: windows
    ldflags:
      - -s -w -X github.com/joemiller/vault-token-helper/cmd.version={{.Version}}+{{.ShortCommit}}
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
github
  # cross-compile static linux bin on macos using https://github.com/FiloSottile/homebrew-musl-cross
  #   brew install FiloSottile/musl-cross/musl-cross
  - binary: vault-token-helper
    id: linux
    ldflags:
      - -s -w -X github.com/joemiller/vault-token-helper/cmd.version={{.Version}}+{{.ShortCommit}}
      - "-linkmode external -extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
    goos:
      - linux
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

# GPG signing
signs:
  - artifacts: checksum

archives:
  # binary-only releasess - all platforms
  - id: binaries
    builds: ["linux", "macos", "windows"]
    format: binary
  # archive releases containg: binary, readme, and license. tarballs (macos, linux), zip (windows)
  - id: archives
    builds: ["linux", "macos", "windows"]
    format_overrides:
      - goos: windows
        format: zip

# homebrew (macos)
brews:
  - ids:
      - archives
    tap:
      owner: joemiller
      name: homebrew-taps
    commit_author:
      name: joe miller
      email: goreleaser@joemiller.me
    folder: Formula
    homepage: "https://github.com/joemiller/vault-token-helper"
    description: "Cross-platform @hashicorp Vault token helper"
    caveats: |
      Run this to create the ~/.vault file. This will configure vault to use the token helper:

        vault-token-helper enable

    dependencies:
      - vault

# deb, rpm packages (linux)
nfpms:
  - id: "vault-token-helper"
    builds: ["linux"]
    vendor: "Joe Miller"
    homepage: "https://github.com/joemiller/vault-token-helper"
    description: "Cross-platform @hashicorp Vault token helper"
    maintainer: "vault-token-helper@joemiller.me"
    license: MIT
    formats:
      - deb
      - rpm
    overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
        replacements:
          amd64: x86_64
          386: i686
          arm: armhfp
          arm64: aarch64
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
        replacements:
          386: i386
          arm: armel
